# Shopify Sales Analysis #

## 1. Introduction

The Shopify Sales Dataset contains transactional data from an e-commerce platform, including information about orders, products, customers, pricing, discounts, shipping costs, ratings, and returns.

 ## 2. Import libraries

In [160]:
import pandas as pd
from sqlalchemy import create_engine
import os
from dotenv import load_dotenv

## 3. Load Dataset

In [161]:
df = pd.read_csv("shopify_sales_dataset.csv")
df.head()

,order_id,order_date,customer_id,product_id,product_category,product_price,discount_percent,quantity,customer_country,traffic_source,payment_method,shipping_cost,rating,is_returned,discounted_price,revenue,profit
0,1,2023-04-13,14958,7824,Accessories,143.39,40,1,USA,Paid Ads,Credit Card,21.08,2.0,0,86.03,86.03,64.95
1,2,2024-03-11,26825,5557,Sports,746.49,15,4,UAE,Email,PayPal,5.48,3.7,0,634.52,2538.08,2532.60
2,3,2025-05-10,37450,2225,Electronics,641.06,5,5,Canada,Paid Ads,Apple Pay,11.27,3.2,0,609.01,3045.05,3033.78
3,4,2023-09-28,20691,7855,Footwear,512.39,0,3,UAE,Direct,Apple Pay,19.22,1.1,0,512.39,1537.17,1517.95
4,5,2023-04-17,24631,7789,Sports,415.89,25,3,UAE,Social Media,Debit Card,24.94,4.1,0,311.92,935.76,910.82

## 4. Understand the Data

In [162]:
df.shape

(60000, 17)

In [163]:
df.describe()

,order_id,customer_id,product_id,product_price,discount_percent,quantity,shipping_cost,rating,is_returned,discounted_price,revenue,profit
count,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000
mean,30000.500000,30035.075600,4504.738650,403.427068,18.151500,3.009567,13.521758,3.002440,0.148117,330.220212,994.098926,980.577168
std,17320.652413,11540.753215,2018.287018,230.045257,12.527663,1.414794,6.627934,1.152265,0.355219,197.114822,806.445785,806.508355
min,1.000000,10000.000000,1000.000000,5.010000,0.000000,1.000000,2.000000,1.000000,0.000000,3.080000,3.080000,-20.490000
25%,15000.750000,20037.750000,2751.750000,203.160000,5.000000,2.000000,7.760000,2.000000,0.000000,161.957500,355.620000,341.925000
50%,30000.500000,30079.000000,4503.500000,403.855000,20.000000,3.000000,13.580000,3.000000,0.000000,322.560000,760.470000,747.275000
75%,45000.250000,40036.250000,6257.000000,603.135000,30.000000,4.000000,19.230000,4.000000,0.000000,482.242500,1462.450000,1449.807500
max,60000.000000,49999.000000,7999.000000,799.990000,40.000000,5.000000,25.000000,5.000000,1.000000,799.900000,3999.500000,3989.950000

In [164]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          60000 non-null  int64
 1   order_date        60000 non-null  str
 2   customer_id       60000 non-null  int64
 3   product_id        60000 non-null  int64
 4   product_category  60000 non-null  str
 5   product_price     60000 non-null  float64
 6   discount_percent  60000 non-null  int64
 7   quantity          60000 non-null  int64
 8   customer_country  60000 non-null  str
 9   traffic_source    60000 non-null  str
 10  payment_method    60000 non-null  str
 11  shipping_cost     60000 non-null  float64
 12  rating            60000 non-null  float64
 13  is_returned       60000 non-null  int64
 14  discounted_price  60000 non-null  float64
 15  revenue           60000 non-null  float64
 16  profit            60000 non-null  float64
dtypes: float64(6), int64(6), str(5)
memory usage: 7.8 MB

## 5. Check missing values

In [165]:
df.isnull().sum()

order_id            0
order_date          0
customer_id         0
product_id          0
product_category    0
product_price       0
discount_percent    0
quantity            0
customer_country    0
traffic_source      0
payment_method      0
shipping_cost       0
rating              0
is_returned         0
discounted_price    0
revenue             0
profit              0
dtype: int64

## 6. Exploratory Data Analysis

### A. Overall Business Performance

In [166]:
total_revenue = df['revenue'].sum().round(2)
total_profit = df['profit'].sum().round(2)

total_revenue, total_profit

(np.float64(59645935.58), np.float64(58834630.1))

### B. Profitability Check

In [167]:
df['Profit Margin'] = df['profit']/df['revenue']
df['Profit Margin'].describe()

count    60000.000000
mean         0.952045
std          0.146070
min         -6.652597
25%          0.962137
50%          0.983995
75%          0.992343
max          0.999491
Name: Profit Margin, dtype: float64

### C. Top Customers

In [168]:
top_customers = df.groupby('customer_id')['revenue'].sum().sort_values(ascending = False)
top_customers.head(5)

customer_id
40873    12955.07
27889    12462.80
15933    11917.52
34270    11654.95
24933    11362.36
Name: revenue, dtype: float64

 Top customers contribute significant portion of revenue

### D. Product Performance

In [169]:
df.groupby('product_id')['revenue'].sum().sort_values(ascending = False).head(5)

product_id
3345    26020.15
3075    24599.69
3021    24038.95
6534    23876.33
6577    23671.35
Name: revenue, dtype: float64

Few products dominate revenue generation

### E. Discount Analysis

In [170]:
df.groupby('discount_percent')['revenue'].mean()

discount_percent
0     1201.895354
5     1164.717318
10    1088.680441
15    1041.791812
20     973.394752
25     905.904865
30     857.993470
40     721.339733
Name: revenue, dtype: float64

Higher discount decrease revenue

### F. Rating Analysis

In [171]:
df.groupby('rating')['revenue'].mean().sort_values(ascending = False).head(5)

rating
4.8    1037.971410
3.8    1035.779565
1.5    1035.585543
2.3    1026.836900
4.0    1024.419141
Name: revenue, dtype: float64

### G. Shipping Cost Impact

In [172]:
df[['shipping_cost', 'revenue', 'profit']].corr()

               shipping_cost   revenue    profit
shipping_cost       1.000000 -0.005331 -0.013549
revenue            -0.005331  1.000000  0.999966
profit             -0.013549  0.999966  1.000000

### Connenting to PostgreSQL

In [173]:
load_dotenv(dotenv_path=".env")

engine = create_engine(
    f"postgresql+psycopg2://{os.getenv('DB_USER')}:{os.getenv('DB_PASS')}"
    f"@{os.getenv('DB_HOST')}:{os.getenv('DB_PORT')}/{os.getenv('DB_NAME')}"
)

print("Connected successfully")

Connected successfully